[package]
name = "meilisearch-tokenizer"
version = "0.1.0"
license = "MIT"
authors = ["Many <many@meilisearch.com>"]
edition = "2018"

[dependencies]
once_cell = "1.4"
whatlang = "0.9.0"
unicode-segmentation = "1.6.0"
jieba-rs = "0.6"
deunicode = "1.1.1"
slice-group-by = "0.2.6"
